using ETWAnalyzer.Extract;
using ETWAnalyzer.ProcessTools;
using System.IO;
using System.Linq;

namespace ETWAnalyzerReaderTest
{
    /// <summary>
    /// This shows how you can access extract ETW data programatically via the IETWExtract interface which gives
    /// you access to CPU/Process/Disk/File ... aggregated per process metrics. 
    /// </summary>
    internal class Program
    {
        static void Main(string[] args)
        {
            if( args.Length == 0 )
            {
                ColorConsole.WriteEmbeddedColorLine($"[green]ETWAnalyzer.Reader.Example pathToJson7zFile[/green]");
                ColorConsole.WriteEmbeddedColorLine($"This simple example will dump the top 10 processes which consume most CPU from an already extracted etl file generated by ETWAnalyzer -extract all -fd xx.etl.");
                return;
            }

            string jsonzFile = args[0];

            if (!File.Exists(jsonzFile))
            {
                ColorConsole.WriteEmbeddedColorLine($"[red]Error: File {jsonzFile} was not found.[/red]");
                return;
            }
            ColorConsole.WriteEmbeddedColorLine($"Dumping contents of file {jsonzFile}");
            TestRunData data = new TestRunData(jsonzFile);


            foreach(var file in data.AllFiles)
            {
                foreach(var cpu in file.Extract.CPU.PerProcessCPUConsumptionInMs.Take(10))
                {
                    ColorConsole.WriteEmbeddedColorLine($"[red]{cpu.Key}[/red]: [green]{cpu.Value:N0}[/green] ms");
                }
            }
        }
    }
}
